version: '3.6'

services:
  db:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./${DUMP_DIR}:/tmp/dumps
      - ./${DUMP_DIR}/${DB_DUMP}:/docker-entrypoint-initdb.d/02dump.sql

#  cache:
#    image: redis:7
#    container_name: cache
#    restart: always
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/data
#    command: redis-server --save 60 1 --loglevel warning

  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    expose:
      - 8080
    container_name: app
    depends_on:
      - db

#  frontend:

#  fluentbit:
#    image: fluent/fluent-bit:2.2.0
#    container_name: fluentbit
#    ports:
#      - "24224:24224"
#      - "24224:24224/udp"
#    volumes:
#      - /var/lib/docker/containers:/var/lib/docker/containers:ro
#      - ./fluentbit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
#      - ./fluentbit/parsers.conf:/fluent-bit/etc/parsers.conf
#    restart: unless-stopped

volumes:
  pg_data:
#  redis_data: